project_id = "wpxhmajdeunabximyfln"

[functions.send-password-reset]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.handle-money-transfer]
verify_jwt = true
