project_id = "wpxhmajdeunabximyfln"

[functions.check-transaction-description]
verify_jwt = true

[functions.suggest-transaction-fields]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.handle-money-transfer]
verify_jwt = true

[functions.vacation-status-notification]
verify_jwt = true

[functions.send-event-notification]
verify_jwt = true

[functions.birthday-notifications]
verify_jwt = false

[functions.overdue-reports-check]
verify_jwt = false

[functions.voice-transaction]
verify_jwt = false

[functions.warehouse-notifications]
verify_jwt = false
