// Утилита для автоматической генерации SKU на основе названия товара

const transliterationMap: Record<string, string> = {
  'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'e',
  'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm',
  'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
  'ф': 'f', 'х': 'h', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'sch', 'ъ': '',
  'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya',
  'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'E',
  'Ж': 'Zh', 'З': 'Z', 'И': 'I', 'Й': 'Y', 'К': 'K', 'Л': 'L', 'М': 'M',
  'Н': 'N', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'У': 'U',
  'Ф': 'F', 'Х': 'H', 'Ц': 'Ts', 'Ч': 'Ch', 'Ш': 'Sh', 'Щ': 'Sch', 'Ъ': '',
  'Ы': 'Y', 'Ь': '', 'Э': 'E', 'Ю': 'Yu', 'Я': 'Ya'
};

/**
 * Транслитерация русского текста в латиницу
 */
function transliterate(text: string): string {
  return text
    .split('')
    .map(char => transliterationMap[char] || char)
    .join('');
}

/**
 * Генерирует SKU на основе названия товара
 * @param name Название товара
 * @returns Сгенерированный SKU вида PREFIX-NUM (например, KP-7531 для "Костюм Пирата")
 */
export function generateSKU(name: string): string {
  if (!name || name.trim().length === 0) {
    return `WH-${Math.floor(1000 + Math.random() * 9000)}`;
  }

  // Убираем лишние пробелы и разбиваем на слова
  const words = name.trim().split(/\s+/).filter(word => word.length > 0);
  
  // Берем первые буквы каждого слова (максимум 4 слова)
  const prefix = words
    .slice(0, 4)
    .map(word => {
      // Убираем специальные символы и берем первую букву
      const cleanWord = word.replace(/[^а-яА-ЯёЁa-zA-Z0-9]/g, '');
      return cleanWord.charAt(0).toUpperCase();
    })
    .join('');

  // Транслитерируем в латиницу
  const transliteratedPrefix = transliterate(prefix);
  
  // Генерируем 4-значное случайное число
  const randomNum = Math.floor(1000 + Math.random() * 9000);
  
  // Формируем финальный SKU
  return `${transliteratedPrefix}-${randomNum}`;
}

/**
 * Проверяет, был ли SKU сгенерирован автоматически
 */
export function isAutoGeneratedSKU(sku: string): boolean {
  // Автогенерированные SKU имеют формат LETTERS-NNNN
  return /^[A-Z]{1,4}-\d{4}$/.test(sku);
}
