// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpxhmajdeunabximyfln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndweGhtYWpkZXVuYWJ4aW15ZmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTM1MTEsImV4cCI6MjA3MTA4OTUxMX0.urAxl_XVwNggHZ1SuwlFFRzuRJSOHAHW038S57YDFzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});